### ISSUE TITLE
Permanently enable features

### ISSUE THREAD

**Issue by walski** [mishamyrt/Lilex#3]
Hey, is there a way I can build this font while permanently enabling features on it? I want to use it in an editor where it seems as if I cannot access the variants offered through it's configuration. So would it be possible to turn them from toggle-able features to always-on features of the built TTF?

Thanks for your help and for putting together this great font in general.

**Comment by mishamyrt** [comment]
Thank you for your request. Such a builder will be added in version 2.100

**Comment by Finii** [comment]
@walski Well, there is the [opentype feature freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer). You can specify which alternative glyphs you want and it recreates a new font for you that can be used with applications that do not support open type features.

For example if you like a slashed zero in Lilex, instead of the default dotted one.
The feature is called 'SS03' (see main page of this repo).
You can specify multiple features as comma separated list (no blanks).

```
$ pip3 install --user --upgrade opentype-feature-freezer
$ pyftfeatfreeze -f 'ss03' ~/Downloads/lilex/Lilex-2.000/ttf/Lilex-Regular.ttf Lilex-Regular-SS03.ttf
$ fontforge ~/Downloads/lilex/Lilex-2.000/ttf/Lilex-Regular.ttf Lilex-Regular-SS03.ttf
```

![image](https://user-images.githubusercontent.com/16012374/229181942-ddacea53-03cf-4818-9ad7-e0d3d19b246e.png)

**Comment by Finii** [comment]
Oh, learned something new today, there is an online freezer available now, no install needed on your side.
Just open the web page, upload the font and try it out https://mutsuntsai.github.io/fontfreeze/

Repo: https://github.com/mutsuntsai/fontfreeze

**Comment by mishamyrt** [comment]
> The way FontFreeze deactivates a feature is by removing all lookups inside it, and it activates a feature by moving all lookups in it into calt, which is usually activated by default in most environments

Same [here](https://github.com/mishamyrt/Lilex/commit/c4bc38057710b6cdee19fd07ae04736fd4fdac76).
