### ISSUE TITLE
The font is lacking Greek characters, as opposed to a picture in the README

### ISSUE THREAD

**Issue by acid-bong** [mishamyrt/Lilex#35]
I'm using Nerd-patched Lilex and it doesn't have Greek letters in it: couldn't find them in Gucharmap, and dwm's rendering shows me that the font lacks these glyphs (it draws glyphs from non-default fonts in a smaller size).
![изображение](https://github.com/mishamyrt/Lilex/assets/94849097/6a4b5916-f8ff-4520-b2d3-bbc926c65b2d)

I wondered if that's an issue on the Nerd's side, but no: the test page also shows that the font lacks Greek letters
![изображение](https://github.com/mishamyrt/Lilex/assets/94849097/ba6d24a6-58b6-47a2-9203-e040cbd7ed18)

**Comment by mishamyrt** [comment]
Indeed, something had gone wrong with them. I'll take a closer look tomorrow and try to fix it

**Comment by mishamyrt** [comment]
Turns out I misunderstood the IBM Plex description. I thought they claimed support for Cyrillic, Latin and Greek for all 3 fonts (Sans, Serif and Mono), but that is not the case. IBM Plex Mono does not support Greek.

But I don't like to lie, and if I claim support, I should add it. There will be Greek support in the 2.500 release!
![image](https://github.com/mishamyrt/Lilex/assets/19162401/5fac6971-bb42-465b-8f5b-5bcab8192934)
