### ISSUE TITLE
Makefile is good

### ISSUE THREAD

**Issue by alexmyczko** [mishamyrt/Lilex#7]
... but the dependency on must use venv not so much. Quickly looking at the `Makefile`, it should be possible to
build the font without venv from source. Would you accept such patches? (Asking because well then I might want to create a Debian package of the font)

**Comment by mishamyrt** [comment]
If you can make a build system that can do all the same things (hardcoding features, substituting ligatures at build time, etc.) then sure, I would be glad.

**Comment by alexmyczko** [comment]
Ok looking at http://sid.ethz.ch/debian/fonts-lilex/fonts-lilex-2.100/requirements.txt

We're (for Debian unstable) stuck at:

```
fontmake==3.5.1   (only have 2.4.1)
cu2qu==1.6.7         (n/a)
gftools==0.9.27    (only have 0.5.2)
glyphsLib==6.2.1 (only have 6.0.6)
arrrgs==2.0.0      (n/a)
ruff==0.0.259      (n/a)
pylint==2.17.1    (only have 2.16.2)
```

**Comment by mishamyrt** [comment]
I don't really want to be stuck with old versions just because they aren't available on Debian Unstable. Can we have a separate `requirements.deb.txt' for that? Also, we could remove `ruff` and `pylint` from there, which aren't needed for the build.

And add another workflow to make sure the build still works and that I didn't break it by adding new features.

**Comment by alexmyczko** [comment]
Don't worry, a requirements.deb.txt is not needed, up to debian maintainer to solve it. But the hint ruff+pylint not needed for build is helpful indeed. Thank you
